stages:
  - build

build:
  stage: build
  image: docker:stable

  services:
    - name: postgres:13.3
      variables:
        POSTGRES_DB: "money_saver"
        POSTGRES_USER: "money_saver"
        POSTGRES_PASSWORD: "change_me"

  script:
    - docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASS} https://lab.knrg.su:5000
    - docker build -t lab.knrg.su:5000/iskonstantin/moneysaver-backend .
    - docker push lab.knrg.su:5000/iskonstantin/moneysaver-backend