build:
  stage: build
  script:
    - cd building
    - ./build.sh
  artifacts:
    paths:
      - building/MoneySaver.jar
      - building/log.xml
deploy:
  stage: deploy
  script:
    - cd building
    - sudo BRANCH=master ./push.sh