stages:
  - build

build:
  stage: build

  services:
    - name: postgres:13.3
      variables:
        POSTGRES_DB: "money_saver"
        POSTGRES_USER: "money_saver"
        POSTGRES_PASSWORD: "change_me"

    - name: docker:dind
      alias: dockerhost
      entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]

  image: docker:stable

  variables:
    DOCKER_HOST: tcp://dockerhost:2375
  script:
    - docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASS} https://lab.knrg.su:5000
    - docker build -t lab.knrg.su:5000/iskonstantin/moneysaver-backend .
    - docker push lab.knrg.su:5000/iskonstantin/moneysaver-backend